// Données de définitions du jeu — source unique importée par le seed (écrit en base)
// ET par le simulateur (packages/game-sim). Ne pas dupliquer ailleurs.

export const BUILDINGS = [
  { id: 'mineraiMine', name: 'Mine de minerai', description: 'Produit du minerai, ressource de base.', baseCostMinerai: 60, baseCostSilicium: 15, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 45, maxLevel: 25, categoryId: 'building_extraction', sortOrder: 0, role: 'producer_minerai', flavorText: "Creusant profondement dans la croute planetaire, les foreuses extractrices de minerai constituent la colonne vertebrale de toute economie spatiale.", prerequisites: [] as { buildingId: string; level: number }[], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'siliciumMine', name: 'Mine de silicium', description: 'Produit du silicium.', baseCostMinerai: 48, baseCostSilicium: 24, baseCostHydrogene: 0, costFactor: 1.6, baseTime: 45, maxLevel: 25, categoryId: 'building_extraction', sortOrder: 1, role: 'producer_silicium', flavorText: "Les gisements de silicium, formes sous des pressions immenses, alimentent l'ensemble des technologies avancees de la galaxie.", prerequisites: [], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'hydrogeneSynth', name: "Synthétiseur d'hydrogène", description: "Produit de l'hydrogène.", baseCostMinerai: 225, baseCostSilicium: 75, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 45, maxLevel: 25, categoryId: 'building_extraction', sortOrder: 2, role: 'producer_hydrogene', flavorText: "L'hydrogene, element fondamental de l'univers, est extrait des oceans planetaires par un processus de filtration moleculaire.", prerequisites: [], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'solarPlant', name: 'Centrale solaire', description: "Produit de l'énergie.", baseCostMinerai: 75, baseCostSilicium: 30, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 45, maxLevel: 25, categoryId: 'building_energie', sortOrder: 0, role: 'producer_energy', flavorText: "D'immenses panneaux photovoltaiques captent l'energie de l'etoile la plus proche pour alimenter l'ensemble des infrastructures planetaires.", prerequisites: [], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'robotics', name: 'Usine de robots', description: 'Réduit le temps de construction des bâtiments.', baseCostMinerai: 400, baseCostSilicium: 120, baseCostHydrogene: 200, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_industrie', sortOrder: 0, role: null, flavorText: "Les chaines de montage automatisees accelerent la construction de tous les batiments et infrastructures.", prerequisites: [] },
  { id: 'shipyard', name: 'Chantier spatial', description: 'Débloque et construit tous les vaisseaux.', baseCostMinerai: 400, baseCostSilicium: 200, baseCostHydrogene: 100, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_industrie', sortOrder: 1, role: null, flavorText: "Le chantier spatial assemble les vaisseaux industriels necessaires a l'expansion de votre empire.", prerequisites: [{ buildingId: 'robotics', level: 1 }] },
  { id: 'arsenal', name: 'Arsenal planétaire', description: 'Débloque et construit les défenses planétaires.', baseCostMinerai: 400, baseCostSilicium: 200, baseCostHydrogene: 100, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_militaire', sortOrder: 0, role: null, flavorText: "L'arsenal planetaire fabrique les systemes de defense qui protegent vos installations contre les attaques ennemies.", prerequisites: [{ buildingId: 'robotics', level: 2 }] },
  { id: 'researchLab', name: 'Laboratoire de recherche', description: 'Permet les recherches.', baseCostMinerai: 200, baseCostSilicium: 400, baseCostHydrogene: 200, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 0, role: null, flavorText: "Au coeur de ce laboratoire, les meilleurs scientifiques de l'empire repoussent les frontieres de la connaissance.", prerequisites: [], allowedPlanetTypes: ['homeworld'] },
  { id: 'storageMinerai', name: 'Entrepôt de minerai', description: 'Augmente le stockage de minerai.', baseCostMinerai: 1000, baseCostSilicium: 0, baseCostHydrogene: 0, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_stockage', sortOrder: 0, role: 'storage_minerai', flavorText: "De vastes entrepots blindes permettent de stocker des quantites croissantes de minerai en toute securite.", prerequisites: [] },
  { id: 'storageSilicium', name: 'Entrepôt de silicium', description: 'Augmente le stockage de silicium.', baseCostMinerai: 1000, baseCostSilicium: 500, baseCostHydrogene: 0, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_stockage', sortOrder: 1, role: 'storage_silicium', flavorText: "Ces chambres a environnement controle preservent le silicium dans des conditions optimales.", prerequisites: [] },
  { id: 'storageHydrogene', name: "Réservoir d'hydrogène", description: "Augmente le stockage d'hydrogène.", baseCostMinerai: 1000, baseCostSilicium: 1000, baseCostHydrogene: 0, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_stockage', sortOrder: 2, role: 'storage_hydrogene', flavorText: "Des reservoirs cryogeniques haute pression maintiennent l'hydrogene a l'etat liquide pour un stockage maximal.", prerequisites: [] },
  { id: 'planetaryShield', name: 'Bouclier planétaire', description: "Génère un champ de force protégeant la planète. Sa puissance est réglable pour économiser l'énergie. La recherche Blindage augmente sa capacité en combat.", baseCostMinerai: 2000, baseCostSilicium: 2000, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 7200, maxLevel: 25, categoryId: 'building_defense', sortOrder: 0, role: 'planetaryShield', flavorText: "Un dôme d'énergie pure enveloppe la planète. En combat, le bouclier est indestructible et se régénère à chaque round. Il ne protège pas votre flotte, mais tant qu'il n'est pas percé, vos défenses planétaires sont intouchables. Sa puissance est réglable dans les paramètres d'énergie.", prerequisites: [] as { buildingId: string; level: number }[], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'volcanic'] },
  { id: 'labVolcanic', name: 'Forge Volcanique', description: "Annexe de recherche specialisee dans les technologies offensives, exploitant la chaleur extreme du volcanisme.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 1, role: null, flavorText: "Au coeur des coulees de lave, les forges volcaniques exploitent des temperatures impossibles a reproduire artificiellement pour developper des armes devastatrices.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['volcanic'] },
  { id: 'labArid', name: 'Laboratoire Aride', description: "Annexe de recherche specialisee dans les materiaux de blindage, tirant parti des mineraux rares du desert.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 2, role: null, flavorText: "Les conditions extremes du desert permettent de tester des alliages sous des contraintes thermiques et abrasives uniques.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['arid'] },
  { id: 'labTemperate', name: 'Bio-Laboratoire', description: "Annexe de recherche specialisee dans l'optimisation de la production, s'appuyant sur la biodiversite locale.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 3, role: null, flavorText: "La richesse biologique des mondes temperes inspire des procedes d'optimisation energetique et productive sans equivalent.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['temperate'] },
  { id: 'labGlacial', name: 'Cryo-Laboratoire', description: "Annexe de recherche specialisee dans les technologies defensives, exploitant les proprietes cryogeniques.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 4, role: null, flavorText: "Les temperatures proches du zero absolu permettent de developper des supraconducteurs et des boucliers d'une efficacite inegalee.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['glacial'] },
  { id: 'labGaseous', name: 'Nebula-Lab', description: "Annexe de recherche specialisee dans la propulsion, exploitant les courants atmospheriques et les gaz rares.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 5, role: null, flavorText: "Flottant dans l'atmosphere dense des geantes gazeuses, le Nebula-Lab teste des systemes de propulsion dans des conditions extremes.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['gaseous'] },
];

export const PRODUCTION_CONFIG = [
  { id: 'mineraiMine', baseProduction: 30, exponentBase: 1.1, energyConsumption: 10, storageBase: null, tempCoeffA: null, tempCoeffB: null },
  { id: 'siliciumMine', baseProduction: 20, exponentBase: 1.1, energyConsumption: 10, storageBase: null, tempCoeffA: null, tempCoeffB: null },
  { id: 'hydrogeneSynth', baseProduction: 10, exponentBase: 1.1, energyConsumption: 20, storageBase: null, tempCoeffA: 1.36, tempCoeffB: 0.004 },
  { id: 'solarPlant', baseProduction: 20, exponentBase: 1.1, energyConsumption: null, storageBase: null, tempCoeffA: null, tempCoeffB: null },
  { id: 'storage', baseProduction: 5000, exponentBase: 1.1, energyConsumption: null, storageBase: 5000, tempCoeffA: null, tempCoeffB: null },
];
