// Données de définitions du jeu — source unique importée par le seed (écrit en base)
// ET par le simulateur (packages/game-sim). Ne pas dupliquer ailleurs.

export const BUILDINGS = [
  { id: 'mineraiMine', name: 'Mine de minerai', description: 'Produit du minerai, ressource de base.', baseCostMinerai: 60, baseCostSilicium: 15, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 45, maxLevel: 25, categoryId: 'building_extraction', sortOrder: 0, role: 'producer_minerai', flavorText: "Creusant profondement dans la croute planetaire, les foreuses extractrices de minerai constituent la colonne vertebrale de toute economie spatiale.", prerequisites: [] as { buildingId: string; level: number }[], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'siliciumMine', name: 'Mine de silicium', description: 'Produit du silicium.', baseCostMinerai: 48, baseCostSilicium: 24, baseCostHydrogene: 0, costFactor: 1.6, baseTime: 45, maxLevel: 25, categoryId: 'building_extraction', sortOrder: 1, role: 'producer_silicium', flavorText: "Les gisements de silicium, formes sous des pressions immenses, alimentent l'ensemble des technologies avancees de la galaxie.", prerequisites: [], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'hydrogeneSynth', name: "Synthétiseur d'hydrogène", description: "Produit de l'hydrogène.", baseCostMinerai: 225, baseCostSilicium: 75, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 45, maxLevel: 25, categoryId: 'building_extraction', sortOrder: 2, role: 'producer_hydrogene', flavorText: "L'hydrogene, element fondamental de l'univers, est extrait des oceans planetaires par un processus de filtration moleculaire.", prerequisites: [], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'solarPlant', name: 'Centrale solaire', description: "Produit de l'énergie.", baseCostMinerai: 75, baseCostSilicium: 30, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 45, maxLevel: 25, categoryId: 'building_energie', sortOrder: 0, role: 'producer_energy', flavorText: "D'immenses panneaux photovoltaiques captent l'energie de l'etoile la plus proche pour alimenter l'ensemble des infrastructures planetaires.", prerequisites: [], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'temperate', 'volcanic'] },
  { id: 'robotics', name: 'Usine de robots', description: 'Réduit le temps de construction des bâtiments.', baseCostMinerai: 400, baseCostSilicium: 120, baseCostHydrogene: 200, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_industrie', sortOrder: 0, role: null, flavorText: "Les chaines de montage automatisees accelerent la construction de tous les batiments et infrastructures.", prerequisites: [] },
  { id: 'shipyard', name: 'Chantier spatial', description: 'Débloque et construit tous les vaisseaux.', baseCostMinerai: 400, baseCostSilicium: 200, baseCostHydrogene: 100, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_industrie', sortOrder: 1, role: null, flavorText: "Le chantier spatial assemble les vaisseaux industriels necessaires a l'expansion de votre empire.", prerequisites: [{ buildingId: 'robotics', level: 1 }] },
  { id: 'arsenal', name: 'Arsenal planétaire', description: 'Débloque et construit les défenses planétaires.', baseCostMinerai: 400, baseCostSilicium: 200, baseCostHydrogene: 100, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_militaire', sortOrder: 0, role: null, flavorText: "L'arsenal planetaire fabrique les systemes de defense qui protegent vos installations contre les attaques ennemies.", prerequisites: [{ buildingId: 'robotics', level: 2 }] },
  { id: 'researchLab', name: 'Laboratoire de recherche', description: 'Permet les recherches.', baseCostMinerai: 200, baseCostSilicium: 400, baseCostHydrogene: 200, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 0, role: null, flavorText: "Au coeur de ce laboratoire, les meilleurs scientifiques de l'empire repoussent les frontieres de la connaissance.", prerequisites: [], allowedPlanetTypes: ['homeworld'] },
  { id: 'storageMinerai', name: 'Entrepôt de minerai', description: 'Augmente le stockage de minerai.', baseCostMinerai: 1000, baseCostSilicium: 0, baseCostHydrogene: 0, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_stockage', sortOrder: 0, role: 'storage_minerai', flavorText: "De vastes entrepots blindes permettent de stocker des quantites croissantes de minerai en toute securite.", prerequisites: [] },
  { id: 'storageSilicium', name: 'Entrepôt de silicium', description: 'Augmente le stockage de silicium.', baseCostMinerai: 1000, baseCostSilicium: 500, baseCostHydrogene: 0, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_stockage', sortOrder: 1, role: 'storage_silicium', flavorText: "Ces chambres a environnement controle preservent le silicium dans des conditions optimales.", prerequisites: [] },
  { id: 'storageHydrogene', name: "Réservoir d'hydrogène", description: "Augmente le stockage d'hydrogène.", baseCostMinerai: 1000, baseCostSilicium: 1000, baseCostHydrogene: 0, costFactor: 2, baseTime: 60, maxLevel: 25, categoryId: 'building_stockage', sortOrder: 2, role: 'storage_hydrogene', flavorText: "Des reservoirs cryogeniques haute pression maintiennent l'hydrogene a l'etat liquide pour un stockage maximal.", prerequisites: [] },
  { id: 'planetaryShield', name: 'Bouclier planétaire', description: "Génère un champ de force protégeant la planète. Sa puissance est réglable pour économiser l'énergie. La recherche Blindage augmente sa capacité en combat.", baseCostMinerai: 2000, baseCostSilicium: 2000, baseCostHydrogene: 0, costFactor: 1.5, baseTime: 7200, maxLevel: 25, categoryId: 'building_defense', sortOrder: 0, role: 'planetaryShield', flavorText: "Un dôme d'énergie pure enveloppe la planète. En combat, le bouclier est indestructible et se régénère à chaque round. Il ne protège pas votre flotte, mais tant qu'il n'est pas percé, vos défenses planétaires sont intouchables. Sa puissance est réglable dans les paramètres d'énergie.", prerequisites: [] as { buildingId: string; level: number }[], variantPlanetTypes: ['arid', 'gaseous', 'glacial', 'volcanic'] },
  { id: 'labVolcanic', name: 'Forge Volcanique', description: "Annexe de recherche specialisee dans les technologies offensives, exploitant la chaleur extreme du volcanisme.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 1, role: null, flavorText: "Au coeur des coulees de lave, les forges volcaniques exploitent des temperatures impossibles a reproduire artificiellement pour developper des armes devastatrices.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['volcanic'] },
  { id: 'labArid', name: 'Laboratoire Aride', description: "Annexe de recherche specialisee dans les materiaux de blindage, tirant parti des mineraux rares du desert.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 2, role: null, flavorText: "Les conditions extremes du desert permettent de tester des alliages sous des contraintes thermiques et abrasives uniques.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['arid'] },
  { id: 'labTemperate', name: 'Bio-Laboratoire', description: "Annexe de recherche specialisee dans l'optimisation de la production, s'appuyant sur la biodiversite locale.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 3, role: null, flavorText: "La richesse biologique des mondes temperes inspire des procedes d'optimisation energetique et productive sans equivalent.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['temperate'] },
  { id: 'labGlacial', name: 'Cryo-Laboratoire', description: "Annexe de recherche specialisee dans les technologies defensives, exploitant les proprietes cryogeniques.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 4, role: null, flavorText: "Les temperatures proches du zero absolu permettent de developper des supraconducteurs et des boucliers d'une efficacite inegalee.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['glacial'] },
  { id: 'labGaseous', name: 'Nebula-Lab', description: "Annexe de recherche specialisee dans la propulsion, exploitant les courants atmospheriques et les gaz rares.", baseCostMinerai: 8000, baseCostSilicium: 16000, baseCostHydrogene: 8000, costFactor: 2, baseTime: 3600, maxLevel: 25, categoryId: 'building_recherche', sortOrder: 5, role: null, flavorText: "Flottant dans l'atmosphere dense des geantes gazeuses, le Nebula-Lab teste des systemes de propulsion dans des conditions extremes.", prerequisites: [{ buildingId: 'researchLab', level: 6 }], allowedPlanetTypes: ['gaseous'] },
];

export const PRODUCTION_CONFIG = [
  { id: 'mineraiMine', baseProduction: 30, exponentBase: 1.1, energyConsumption: 10, storageBase: null, tempCoeffA: null, tempCoeffB: null },
  { id: 'siliciumMine', baseProduction: 20, exponentBase: 1.1, energyConsumption: 10, storageBase: null, tempCoeffA: null, tempCoeffB: null },
  { id: 'hydrogeneSynth', baseProduction: 10, exponentBase: 1.1, energyConsumption: 20, storageBase: null, tempCoeffA: 1.36, tempCoeffB: 0.004 },
  { id: 'solarPlant', baseProduction: 20, exponentBase: 1.1, energyConsumption: null, storageBase: null, tempCoeffA: null, tempCoeffB: null },
  { id: 'storage', baseProduction: 5000, exponentBase: 1.1, energyConsumption: null, storageBase: 5000, tempCoeffA: null, tempCoeffB: null },
];

export const RESEARCH = [
  { id: 'espionageTech', name: 'Technologie Espionnage', description: "Améliore les sondes d'espionnage.", baseCostMinerai: 200, baseCostSilicium: 1000, baseCostHydrogene: 200, costFactor: 2, levelColumn: 'espionageTech', categoryId: 'research_sciences', sortOrder: 0, flavorText: "Des sondes furtives equipees de capteurs toujours plus performants permettent de percer les secrets de vos adversaires.", effectDescription: "Chaque niveau ameliore la quantite d'informations obtenues par sonde et la resistance au contre-espionnage.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 3 }], research: [] as { researchId: string; level: number }[] } },
  { id: 'computerTech', name: 'Technologie Ordinateur', description: 'Augmente le nombre de flottes simultanées.', baseCostMinerai: 0, baseCostSilicium: 400, baseCostHydrogene: 600, costFactor: 2, levelColumn: 'computerTech', categoryId: 'research_sciences', sortOrder: 1, flavorText: "L'augmentation de la puissance de calcul permet de coordonner un nombre croissant de flottes simultanement.", effectDescription: "Chaque niveau permet de controler une flotte supplementaire simultanement.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 1 }], research: [] } },
  { id: 'energyTech', name: 'Technologie Énergie', description: 'Recherche fondamentale en énergie.', baseCostMinerai: 0, baseCostSilicium: 800, baseCostHydrogene: 400, costFactor: 2, levelColumn: 'energyTech', categoryId: 'research_sciences', sortOrder: 2, flavorText: "La maitrise des flux energetiques ouvre la voie aux technologies de propulsion avancees.", effectDescription: "Chaque niveau augmente la production d'energie de 2%. Prerequis pour les technologies de propulsion avancees.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 1 }], research: [] } },
  { id: 'combustion', name: 'Réacteur à combustion', description: 'Propulsion de base pour les vaisseaux.', baseCostMinerai: 400, baseCostSilicium: 0, baseCostHydrogene: 600, costFactor: 2, levelColumn: 'combustion', categoryId: 'research_propulsion', sortOrder: 3, flavorText: "Les moteurs a combustion interne propulsent les premiers vaisseaux a travers l'espace interstellaire.", effectDescription: "Augmente la vitesse des vaisseaux à combustion avec rendements décroissants : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 1 }], research: [{ researchId: 'energyTech', level: 1 }] } },
  { id: 'impulse', name: 'Réacteur à impulsion', description: 'Propulsion avancée.', baseCostMinerai: 2000, baseCostSilicium: 4000, baseCostHydrogene: 600, costFactor: 2, levelColumn: 'impulse', categoryId: 'research_propulsion', sortOrder: 4, flavorText: "Le reacteur a impulsion utilise le principe de reaction nucleaire pour atteindre des vitesses superieures.", effectDescription: "Augmente la vitesse des vaisseaux à impulsion avec rendements décroissants : +158% au niveau 5, +286% au niveau 20, plafond +300%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 2 }], research: [{ researchId: 'energyTech', level: 1 }] } },
  { id: 'hyperspaceDrive', name: 'Propulsion hyperespace', description: 'Propulsion la plus rapide.', baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 6000, costFactor: 2, levelColumn: 'hyperspaceDrive', categoryId: 'research_propulsion', sortOrder: 5, flavorText: "En pliant l'espace-temps, la propulsion hyperespace permet de parcourir des distances autrefois inimaginables.", effectDescription: "Augmente la vitesse des vaisseaux hyperespace avec rendements décroissants : +237% au niveau 5, +428% au niveau 20, plafond +450%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 7 }], research: [{ researchId: 'energyTech', level: 5 }, { researchId: 'shielding', level: 5 }] } },
  { id: 'weapons', name: 'Technologie Armes', description: 'Augmente les dégâts de 10% par niveau.', baseCostMinerai: 800, baseCostSilicium: 200, baseCostHydrogene: 0, costFactor: 2, levelColumn: 'weapons', categoryId: 'research_combat', sortOrder: 6, flavorText: "Chaque avancee en technologie des armes augmente de 10% la puissance de feu de toutes vos unites.", effectDescription: "Augmente les dégâts de toutes les unités avec rendements décroissants : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 4 }], research: [] } },
  { id: 'shielding', name: 'Technologie Bouclier', description: 'Augmente les boucliers de 10% par niveau.', baseCostMinerai: 200, baseCostSilicium: 600, baseCostHydrogene: 0, costFactor: 2, levelColumn: 'shielding', categoryId: 'research_combat', sortOrder: 7, flavorText: "Les generateurs de bouclier creent des champs de force protegeant vos unites des impacts ennemis.", effectDescription: "Augmente les boucliers de toutes les unités avec rendements décroissants : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 4 }], research: [{ researchId: 'energyTech', level: 3 }] } },
  { id: 'armor', name: 'Technologie Protection', description: 'Augmente la coque et le blindage de 10% par niveau.', baseCostMinerai: 1000, baseCostSilicium: 0, baseCostHydrogene: 0, costFactor: 2, levelColumn: 'armor', categoryId: 'research_combat', sortOrder: 8, flavorText: "Des alliages toujours plus resistants renforcent la coque et le blindage de toutes vos unites de 10% par niveau.", effectDescription: "Augmente la coque et le blindage de toutes les unités avec rendements décroissants : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 2 }], research: [] } },
  { id: 'rockFracturing', name: 'Technologie de fracturation des roches', description: "Ameliore les techniques d'extraction miniere, augmentant la capacite d'extraction des prospecteurs de 15% par niveau.", baseCostMinerai: 2000, baseCostSilicium: 4000, baseCostHydrogene: 1000, costFactor: 2, levelColumn: 'rockFracturing', categoryId: 'research_sciences', sortOrder: 9, flavorText: "Des ondes de choc calibrees fracturent la roche asteroidale, augmentant considerablement la quantite de minerai extraite par vos prospecteurs.", effectDescription: "Augmente la capacité d'extraction des prospecteurs avec rendements décroissants : +118% au niveau 5, +215% au niveau 20, plafond +225%.", maxLevel: 20, prerequisites: { buildings: [], research: [{ researchId: 'combustion', level: 3 }] } },
  // NOTE: deepSpaceRefining has no bonus_definitions entry. Its reduction is multiplicative
  // (0.85^level), incompatible with resolveBonus's linear formula. Computed directly in pve.ts.
  { id: 'deepSpaceRefining', name: 'Raffinage en espace lointain', description: "Developpe des techniques de raffinage embarquees qui reduisent les scories lors de l'extraction miniere.", baseCostMinerai: 2000, baseCostSilicium: 4000, baseCostHydrogene: 1000, costFactor: 2, levelColumn: 'deepSpaceRefining', categoryId: 'research_sciences', sortOrder: 10, flavorText: "Des nanofiltres embarques separent les scories du minerai pur directement dans la soute du prospecteur, maximisant chaque voyage.", effectDescription: "Chaque niveau reduit les scories de 15% (multiplicatif). Niveau 15 : ~2.5% de scories restantes.", maxLevel: 15, prerequisites: { buildings: [], research: [{ researchId: 'rockFracturing', level: 2 }] } },
  { id: 'sensorNetwork', name: 'Réseau de capteurs', description: "Deploie un reseau de capteurs en espace profond pour detecter les flottes hostiles en approche. Plus le niveau est eleve, plus la detection est precoce et detaillee.", baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 10000, costFactor: 2, levelColumn: 'sensorNetwork', categoryId: 'research_combat', sortOrder: 11, flavorText: "Un maillage de balises furtives parseme l'espace autour de vos colonies, detectant toute perturbation gravitationnelle causee par une flotte en approche.", effectDescription: "Chaque niveau ameliore le delai et le detail de detection des attaques entrantes.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 6 }], research: [{ researchId: 'espionageTech', level: 3 }] } },
  { id: 'stealthTech', name: 'Technologie furtive', description: "Developpe des systemes de brouillage et d'occultation pour reduire la detectabilite de vos flottes d'attaque. Contrecarre le reseau de capteurs ennemi.", baseCostMinerai: 15000, baseCostSilicium: 15000, baseCostHydrogene: 10000, costFactor: 2, levelColumn: 'stealthTech', categoryId: 'research_combat', sortOrder: 12, flavorText: "Des generateurs de champ holographique et des absorbeurs d'ondes rendent vos flottes quasi-invisibles aux capteurs ennemis.", effectDescription: "Chaque niveau reduit l'efficacite du reseau de capteurs ennemi, retardant la detection et masquant les informations.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 6 }], research: [{ researchId: 'espionageTech', level: 3 }] } },
  { id: 'semiconductors', name: 'Technologie de semi-conducteurs', description: "Ameliore l'efficacite des circuits de tous les systemes, reduisant leur consommation energetique de 2% par niveau.", baseCostMinerai: 800, baseCostSilicium: 400, baseCostHydrogene: 200, costFactor: 2, levelColumn: 'semiconductors', categoryId: 'research_sciences', sortOrder: 11, flavorText: "Des materiaux semi-conducteurs avances reduisent les pertes thermiques et ameliorent le rendement de tous les systemes energetiques de la colonie.", effectDescription: "Chaque niveau reduit la consommation d'energie de tous les batiments de 2%.", maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 3 }], research: [{ researchId: 'energyTech', level: 1 }] } },
  { id: 'armoredStorage', name: 'Blindage des hangars', description: 'Renforce les hangars pour protéger une partie des ressources contre le pillage.', baseCostMinerai: 1000, baseCostSilicium: 1000, baseCostHydrogene: 0, costFactor: 2, levelColumn: 'armoredStorage', categoryId: 'research_defense', sortOrder: 50, flavorText: 'Un blindage moléculaire rend une partie du stockage totalement inaccessible aux pilleurs.', effectDescription: 'Chaque niveau augmente de 5% la capacité blindée des hangars, protégeant les ressources du pillage.', maxLevel: 20, prerequisites: { buildings: [{ buildingId: 'storageMinerai', level: 2 }], research: [] } },
  { id: 'planetaryExploration', name: 'Exploration planétaire', description: "Permet d'explorer les planètes pour découvrir leurs biomes.", baseCostMinerai: 1000, baseCostSilicium: 2000, baseCostHydrogene: 500, costFactor: 2, levelColumn: 'planetaryExploration', categoryId: 'research_sciences', sortOrder: 15, flavorText: "L'étude approfondie des écosystèmes planétaires révèle des biomes aux propriétés uniques, offrant des avantages stratégiques à ceux qui savent les exploiter.", effectDescription: "Niveau 1 : débloque le vaisseau Explorateur. Chaque niveau augmente les chances de découvrir des biomes lors des missions d'exploration.", maxLevel: null, prerequisites: { buildings: [{ buildingId: 'researchLab', level: 3 }], research: [{ researchId: 'espionageTech', level: 2 }] } },
  { id: 'volcanicWeaponry', name: 'Metallurgie de plasma', description: "Les forges volcaniques permettent de developper des armes d'une puissance superieure.", baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 6000, costFactor: 2, levelColumn: 'volcanicWeaponry', categoryId: 'research_combat', sortOrder: 20, flavorText: "Le plasma en fusion, canalise par des champs magnetiques, produit des projectiles capables de traverser n'importe quel blindage.", effectDescription: "Augmente les dégâts de toutes les unités (cumule avec Armes) : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, requiredAnnexType: 'volcanic', prerequisites: { buildings: [], research: [{ researchId: 'weapons', level: 3 }] } },
  { id: 'aridArmor', name: 'Blindage composite', description: "Les mineraux rares du desert permettent de creer des alliages de coque et de blindage ultra-resistants.", baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 6000, costFactor: 2, levelColumn: 'aridArmor', categoryId: 'research_combat', sortOrder: 21, flavorText: "Des fibres minerales entrelacees avec des nano-polymeres forment un blindage composite capable d'absorber des impacts devastateurs.", effectDescription: "Augmente la coque et le blindage de toutes les unités (cumule avec Protection) : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, requiredAnnexType: 'arid', prerequisites: { buildings: [], research: [{ researchId: 'armor', level: 3 }] } },
  { id: 'temperateProduction', name: 'Symbiose adaptative', description: "L'etude des ecosystemes temperes ameliore l'efficacite de toutes les chaines de production.", baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 6000, costFactor: 2, levelColumn: 'temperateProduction', categoryId: 'research_sciences', sortOrder: 22, flavorText: "Des micro-organismes symbiotiques, adaptes a chaque processus industriel, optimisent la production de toutes les ressources.", effectDescription: "Chaque niveau augmente la production de toutes les ressources de 2%.", maxLevel: 20, requiredAnnexType: 'temperate', prerequisites: { buildings: [], research: [{ researchId: 'energyTech', level: 3 }] } },
  { id: 'glacialShielding', name: 'Bouclier cryogenique', description: "Les supraconducteurs cryogeniques permettent de creer des boucliers d'une efficacite inegalee.", baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 6000, costFactor: 2, levelColumn: 'glacialShielding', categoryId: 'research_combat', sortOrder: 23, flavorText: "Des circuits supraconducteurs refroidis a des temperatures proches du zero absolu generent des champs de force d'une stabilite parfaite.", effectDescription: "Augmente les boucliers de toutes les unités (cumule avec Bouclier) : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, requiredAnnexType: 'glacial', prerequisites: { buildings: [], research: [{ researchId: 'shielding', level: 3 }] } },
  { id: 'gaseousPropulsion', name: 'Propulsion ionique avancee', description: "Les gaz rares des geantes gazeuses alimentent des moteurs d'une vitesse inegalee.", baseCostMinerai: 10000, baseCostSilicium: 20000, baseCostHydrogene: 6000, costFactor: 2, levelColumn: 'gaseousPropulsion', categoryId: 'research_propulsion', sortOrder: 24, flavorText: "Des ions lourds extraits de l'atmosphere dense sont acceleres a des vitesses relativistes, propulsant les vaisseaux au-dela de toutes les limites connues.", effectDescription: "Augmente la vitesse de tous les vaisseaux : +79% au niveau 5, +143% au niveau 20, plafond +150%.", maxLevel: 20, requiredAnnexType: 'gaseous', prerequisites: { buildings: [], research: [{ researchId: 'impulse', level: 3 }] } },
];

// ── Ship data (merged: ships + combat-stats + ship-stats) ──

export const SHIPS = [
  // Industrial ships → shipyard
  { id: 'prospector', name: 'Prospecteur', description: "Vaisseau minier pour l'extraction de ressources.", costMinerai: 2250, costSilicium: 750, costHydrogene: 375, countColumn: 'prospector', baseSpeed: 3000, fuelConsumption: 50, cargoCapacity: 750, driveType: 'combustion', weapons: 1, shield: 8, hull: 15, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', miningExtraction: 3000, categoryId: 'ship_utilitaire', sortOrder: 0, role: 'mining', flavorText: "Le prospecteur est un vaisseau minier leger concu pour l'extraction de ressources sur les asteroides et planetes voisines.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 2 }], research: [] } },
  { id: 'recuperateur', name: 'Récupérateur', description: "Mini recycleur early-game pour collecter les débris spatiaux.", costMinerai: 2250, costSilicium: 750, costHydrogene: 375, countColumn: 'recuperateur', baseSpeed: 2000, fuelConsumption: 15, cargoCapacity: 2000, driveType: 'combustion', weapons: 1, shield: 10, hull: 20, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_utilitaire', sortOrder: 1, role: 'recycling', flavorText: "Compact et economique, le recuperateur est le premier vaisseau capable de collecter les debris des batailles spatiales. Sa petite soute le rend ideal pour les jeunes empires.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 4 }], research: [{ researchId: 'combustion', level: 1 }] } },
  { id: 'smallCargo', name: 'Petit transporteur', description: 'Transport léger de ressources.', costMinerai: 1500, costSilicium: 1500, costHydrogene: 0, countColumn: 'smallCargo', baseSpeed: 5000, fuelConsumption: 10, cargoCapacity: 5000, driveType: 'combustion', weapons: 1, shield: 8, hull: 12, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_transport', sortOrder: 2, role: 'transport', flavorText: "Rapide et maniable, le petit transporteur est le cheval de trait de toute flotte commerciale.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 2 }], research: [{ researchId: 'combustion', level: 2 }] } },
  { id: 'largeCargo', name: 'Grand transporteur', description: 'Transport lourd de ressources.', costMinerai: 4500, costSilicium: 4500, costHydrogene: 0, countColumn: 'largeCargo', baseSpeed: 7500, fuelConsumption: 50, cargoCapacity: 25000, driveType: 'combustion', weapons: 1, shield: 20, hull: 36, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_transport', sortOrder: 3, role: 'transport', flavorText: "Avec sa soute massive, le grand transporteur peut deplacer d'enormes quantites de ressources en un seul voyage.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 4 }], research: [{ researchId: 'combustion', level: 6 }] } },
  { id: 'espionageProbe', name: "Sonde d'espionnage", description: 'Sonde rapide pour espionner.', costMinerai: 0, costSilicium: 750, costHydrogene: 0, countColumn: 'espionageProbe', baseSpeed: 100000000, fuelConsumption: 1, cargoCapacity: 0, driveType: 'combustion', weapons: 0, shield: 0, hull: 3, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_utilitaire', sortOrder: 4, role: 'espionage', flavorText: "Quasiment indetectable, la sonde d'espionnage collecte des renseignements precieux sur les planetes adverses.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 3 }], research: [{ researchId: 'combustion', level: 3 }, { researchId: 'espionageTech', level: 2 }] } },
  { id: 'colonyShip', name: 'Vaisseau de colonisation', description: 'Colonise de nouvelles planètes.', costMinerai: 7500, costSilicium: 15000, costHydrogene: 7500, countColumn: 'colonyShip', baseSpeed: 2500, fuelConsumption: 1000, cargoCapacity: 7500, driveType: 'impulse', weapons: 4, shield: 80, hull: 90, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_utilitaire', sortOrder: 5, role: 'colonization', flavorText: "Ce vaisseau transporte tout le necessaire pour etablir une nouvelle colonie sur une planete inhabitee.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 4 }], research: [{ researchId: 'impulse', level: 3 }] } },
  { id: 'recycler', name: 'Recycleur', description: 'Collecte les champs de débris.', costMinerai: 7500, costSilicium: 4500, costHydrogene: 1500, countColumn: 'recycler', baseSpeed: 2000, fuelConsumption: 300, cargoCapacity: 20000, driveType: 'combustion', weapons: 1, shield: 8, hull: 48, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_utilitaire', sortOrder: 6, role: 'recycling', flavorText: "Equipe de puissants aimants et de bras mecaniques, le recycleur collecte les debris des batailles spatiales.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 4 }], research: [{ researchId: 'combustion', level: 6 }, { researchId: 'shielding', level: 2 }] } },
  { id: 'solarSatellite', name: 'Satellite solaire', description: "Produit de l'énergie en orbite. Ne peut pas être envoyé en mission.", costMinerai: 0, costSilicium: 1500, costHydrogene: 375, countColumn: 'solarSatellite', baseSpeed: 0, fuelConsumption: 0, cargoCapacity: 0, driveType: 'combustion', weapons: 1, shield: 1, hull: 6, baseArmor: 0, shotCount: 1, combatCategoryId: 'support', categoryId: 'ship_utilitaire', sortOrder: 7, role: 'energy', flavorText: "En orbite stationnaire, les satellites solaires captent l'énergie stellaire et la transmettent aux installations planétaires. Plus la planète est proche de son étoile, plus ils sont efficaces.", isStationary: true, prerequisites: { buildings: [{ buildingId: 'shipyard', level: 1 }], research: [] } },
  { id: 'explorer', name: 'Explorateur', description: "Vaisseau scientifique d'exploration planétaire.", costMinerai: 2250, costSilicium: 1500, costHydrogene: 375, countColumn: 'explorer', baseSpeed: 8000, fuelConsumption: 20, cargoCapacity: 0, driveType: 'combustion', weapons: 0, shield: 5, hull: 10, baseArmor: 0, shotCount: 0, combatCategoryId: 'support', categoryId: 'ship_utilitaire', sortOrder: 8, role: 'exploration', flavorText: "Équipé de capteurs avancés et de laboratoires embarqués, l'explorateur analyse la composition des planètes pour révéler leurs biomes cachés.", prerequisites: { buildings: [{ buildingId: 'shipyard', level: 3 }], research: [{ researchId: 'planetaryExploration', level: 1 }] } },
  // Military ships → shipyard (fusion des chantiers, 2026-06-10)
  { id: 'interceptor', name: 'Intercepteur', description: 'Vaisseau de combat de base.', costMinerai: 2250, costSilicium: 750, costHydrogene: 0, countColumn: 'interceptor', baseSpeed: 12500, fuelConsumption: 20, cargoCapacity: 50, driveType: 'combustion', weapons: 4, shield: 6, hull: 12, baseArmor: 1, shotCount: 3, combatCategoryId: 'light', categoryId: 'ship_combat', sortOrder: 8, role: 'combat', flavorText: "Le chasseur leger, pilier des premieres flottes, compense sa fragilite par son faible cout de production.", weaponProfiles: [
    { damage: 4, shots: 3, targetCategory: 'light', hasChainKill: true },
  ], prerequisites: { buildings: [{ buildingId: 'shipyard', level: 1 }], research: [{ researchId: 'combustion', level: 1 }] } },
  { id: 'frigate', name: 'Frégate', description: 'Vaisseau de combat amélioré.', costMinerai: 4500, costSilicium: 3000, costHydrogene: 0, countColumn: 'frigate', baseSpeed: 10000, fuelConsumption: 75, cargoCapacity: 100, driveType: 'impulse', weapons: 12, shield: 16, hull: 30, baseArmor: 2, shotCount: 2, combatCategoryId: 'medium', categoryId: 'ship_combat', sortOrder: 9, role: 'combat', flavorText: "Blindage renforce et armement superieur font du chasseur lourd un adversaire redoutable en combat rapproche.", weaponProfiles: [
    { damage: 12, shots: 1, targetCategory: 'medium' },
    { damage: 6,  shots: 2, targetCategory: 'light' },
  ], prerequisites: { buildings: [{ buildingId: 'shipyard', level: 3 }], research: [{ researchId: 'armor', level: 2 }, { researchId: 'impulse', level: 2 }] } },
  { id: 'cruiser', name: 'Croiseur', description: 'Vaisseau de guerre polyvalent.', costMinerai: 15000, costSilicium: 5250, costHydrogene: 1500, countColumn: 'cruiser', baseSpeed: 15000, fuelConsumption: 300, cargoCapacity: 800, driveType: 'impulse', weapons: 45, shield: 32, hull: 55, baseArmor: 4, shotCount: 1, combatCategoryId: 'heavy', categoryId: 'ship_combat', sortOrder: 10, role: 'combat', flavorText: "Polyvalent et puissamment arme, le croiseur domine les escarmouches grace a son tir rapide devastateur.", weaponProfiles: [
    { damage: 35, shots: 1, targetCategory: 'heavy' },
    { damage: 6,  shots: 2, targetCategory: 'light', rafale: { category: 'light', count: 6 } },
  ], prerequisites: { buildings: [{ buildingId: 'shipyard', level: 5 }], research: [{ researchId: 'impulse', level: 4 }, { researchId: 'weapons', level: 3 }] } },
  { id: 'battlecruiser', name: 'Cuirassé', description: 'Puissant navire de guerre.', costMinerai: 33750, costSilicium: 11250, costHydrogene: 0, countColumn: 'battlecruiser', baseSpeed: 10000, fuelConsumption: 500, cargoCapacity: 1500, driveType: 'hyperspaceDrive', weapons: 70, shield: 40, hull: 120, baseArmor: 6, shotCount: 1, combatCategoryId: 'heavy', categoryId: 'ship_combat', sortOrder: 11, role: 'combat', flavorText: "Le vaisseau de bataille, colosse d'acier et de feu, est la piece maitresse de toute flotte d'invasion.", weaponProfiles: [
    { damage: 50, shots: 1, targetCategory: 'heavy' },
    { damage: 10, shots: 2, targetCategory: 'medium', rafale: { category: 'medium', count: 4 } },
  ], prerequisites: { buildings: [{ buildingId: 'shipyard', level: 7 }], research: [{ researchId: 'hyperspaceDrive', level: 4 }] } },
];

export const BONUS_DEFINITIONS = [
  { id: 'robotics__building_time', sourceType: 'building', sourceId: 'robotics', stat: 'building_time', percentPerLevel: -15, category: null, statLabel: 'Temps de construction' },
  { id: 'researchLab__research_time', sourceType: 'building', sourceId: 'researchLab', stat: 'research_time', percentPerLevel: -15, category: null, statLabel: 'Temps de recherche' },
  { id: 'shipyard__ship_build_time__build_industrial', sourceType: 'building', sourceId: 'shipyard', stat: 'ship_build_time', percentPerLevel: -15, category: 'build_industrial', statLabel: 'Temps de construction des vaisseaux' },
  { id: 'arsenal__defense_build_time', sourceType: 'building', sourceId: 'arsenal', stat: 'defense_build_time', percentPerLevel: -15, category: null, statLabel: 'Temps de construction des défenses' },
  { id: 'shipyard__ship_build_time__build_military', sourceType: 'building', sourceId: 'shipyard', stat: 'ship_build_time', percentPerLevel: -15, category: 'build_military', statLabel: 'Temps de construction des vaisseaux' },
  { id: 'weapons__weapons', sourceType: 'research', sourceId: 'weapons', stat: 'weapons', percentPerLevel: 10, category: null, statLabel: 'Dégâts des armes' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'shielding__shielding', sourceType: 'research', sourceId: 'shielding', stat: 'shielding', percentPerLevel: 10, category: null, statLabel: 'Puissance des boucliers' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'armor__armor', sourceType: 'research', sourceId: 'armor', stat: 'armor', percentPerLevel: 10, category: null, statLabel: 'Coque et blindage' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'combustion__ship_speed__combustion', sourceType: 'research', sourceId: 'combustion', stat: 'ship_speed', percentPerLevel: 10, category: 'combustion', statLabel: 'Vitesse des vaisseaux' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'impulse__ship_speed__impulse', sourceType: 'research', sourceId: 'impulse', stat: 'ship_speed', percentPerLevel: 20, category: 'impulse', statLabel: 'Vitesse des vaisseaux' , bonusType: 'asymptotic', softCapMax: 3.0, softCapK: 0.15 },
  { id: 'hyperspaceDrive__ship_speed__hyperspaceDrive', sourceType: 'research', sourceId: 'hyperspaceDrive', stat: 'ship_speed', percentPerLevel: 30, category: 'hyperspaceDrive', statLabel: 'Vitesse des vaisseaux' , bonusType: 'asymptotic', softCapMax: 4.5, softCapK: 0.15 },
  { id: 'rockFracturing__mining_extraction', sourceType: 'research', sourceId: 'rockFracturing', stat: 'mining_extraction', percentPerLevel: 15, category: null, statLabel: "Capacité d'extraction" , bonusType: 'asymptotic', softCapMax: 2.25, softCapK: 0.15 },
  { id: 'computerTech__fleet_count', sourceType: 'research', sourceId: 'computerTech', stat: 'fleet_count', percentPerLevel: 100, category: null, statLabel: 'Flottes simultanées' },
  { id: 'energyTech__energy_production', sourceType: 'research', sourceId: 'energyTech', stat: 'energy_production', percentPerLevel: 2, category: null, statLabel: "Production d'énergie" },
  { id: 'semiconductors__energy_consumption', sourceType: 'research', sourceId: 'semiconductors', stat: 'energy_consumption', percentPerLevel: -2, category: null, statLabel: "Consommation d'énergie" },
  { id: 'armoredStorage__armored_storage', sourceType: 'research', sourceId: 'armoredStorage', stat: 'armored_storage', percentPerLevel: 5, category: null, statLabel: 'Protection blindée' },
  { id: 'volcanicWeaponry__weapons', sourceType: 'research', sourceId: 'volcanicWeaponry', stat: 'weapons', percentPerLevel: 10, category: null, statLabel: 'Degats des armes (Forge Volcanique)' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'aridArmor__armor', sourceType: 'research', sourceId: 'aridArmor', stat: 'armor', percentPerLevel: 10, category: null, statLabel: 'Coque et blindage (Laboratoire Aride)' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'temperateProduction__production_minerai', sourceType: 'research', sourceId: 'temperateProduction', stat: 'production_minerai', percentPerLevel: 2, category: null, statLabel: 'Production de minerai (Bio-Laboratoire)' },
  { id: 'temperateProduction__production_silicium', sourceType: 'research', sourceId: 'temperateProduction', stat: 'production_silicium', percentPerLevel: 2, category: null, statLabel: 'Production de silicium (Bio-Laboratoire)' },
  { id: 'temperateProduction__production_hydrogene', sourceType: 'research', sourceId: 'temperateProduction', stat: 'production_hydrogene', percentPerLevel: 2, category: null, statLabel: "Production d'hydrogene (Bio-Laboratoire)" },
  { id: 'glacialShielding__shielding', sourceType: 'research', sourceId: 'glacialShielding', stat: 'shielding', percentPerLevel: 10, category: null, statLabel: 'Puissance des boucliers (Cryo-Laboratoire)' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
  { id: 'gaseousPropulsion__ship_speed', sourceType: 'research', sourceId: 'gaseousPropulsion', stat: 'ship_speed', percentPerLevel: 10, category: null, statLabel: 'Vitesse des vaisseaux (Nebula-Lab)' , bonusType: 'asymptotic', softCapMax: 1.5, softCapK: 0.15 },
];
