-- push_subscriptions : retrait de la colonne `preferences`, remplacee par la
-- table `notification_preferences` (UI supprimee le 2026-03-31, commit 62d0d06d).
--
-- Donnees : 15/15 lignes en prod portent exactement la valeur par defaut
-- (les 6 categories a true), 0 ligne en staging et en test. Aucune information
-- n'est perdue. refresh-staging-from-prod.sh TRUNCATE la table sans nommer de
-- colonne -> non impacte.
--
-- =====================================================================
-- /!\ CETTE MIGRATION NE PEUT PAS PARTIR SEULE. Deploiement INDIVISIBLE :
--   1. retirer le champ de packages/db/src/schema/push-subscriptions.ts
--   2. cette migration
--   3. deployer API + workers EN MEME TEMPS que le DDL
-- Prerequis : le lot 1 est deja deploye (la garde `prefs[category] === false`
-- de push.service.ts a disparu) — c'est le cas depuis le commit 4c3c3b73.
-- =====================================================================
--
-- Pourquoi l'ordre inverse casse la production, et de facon irreparable :
-- `sendToUser` fait `db.select().from(pushSubscriptions)` et Drizzle derive la
-- liste explicite des colonnes depuis le schema TypeScript. Colonne absente en
-- base + schema qui la declare encore = exception a CHAQUE envoi push, sur les
-- 15 abonnements vivants.
--
-- Or dans build-completion.worker.ts, l'appel a sendToUser n'est PAS dans un
-- try/catch et s'execute AVANT l'insertion du game_event, la verification du
-- tutoriel et les hooks de quete journaliere et d'XP d'empire. Le job BullMQ
-- echouerait, et au retry `handler(buildQueueId)` renverrait null (« already
-- completed ») : game_event, progression de tutoriel, quete journaliere et XP
-- seraient DEFINITIVEMENT perdus pour cette construction. Regression
-- silencieuse et non reparable.
--
-- Verification apres deploiement : provoquer une fin de construction et
-- controler qu'aucun job `build-completion` n'est en `failed` dans BullMQ.

ALTER TABLE push_subscriptions DROP COLUMN preferences;
